spring.application.name=event-notificator

server.port=8082

springdoc.swagger-ui.url=/notificator-openapi.yaml
spring.datasource.url=jdbc:postgresql://localhost:5431/postgres
spring.datasource.password=12345
spring.datasource.username=username
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.kafka.consumer.properties.spring.json.use.type.headers=false
jwt.secret-key=78Wrc/XhQnIPPJgBWYstVpTlO0o83958LK48M1H8YMmLmQSjtYpMONdWBLA=
jwt.lifetime=86400000


kafka.bootstrap.servers=localhost:9092
kafka.group.id=notificator-group
kafka.trusted.packages=belkin.dev.events.kafka.dto